#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KutuphaneDB")]
	public partial class KutuphaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertYazar(Yazar instance);
    partial void UpdateYazar(Yazar instance);
    partial void DeleteYazar(Yazar instance);
    partial void InsertKitapTuru(KitapTuru instance);
    partial void UpdateKitapTuru(KitapTuru instance);
    partial void DeleteKitapTuru(KitapTuru instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertTip(Tip instance);
    partial void UpdateTip(Tip instance);
    partial void DeleteTip(Tip instance);
    partial void InsertTur(Tur instance);
    partial void UpdateTur(Tur instance);
    partial void DeleteTur(Tur instance);
    partial void InsertUye(Uye instance);
    partial void UpdateUye(Uye instance);
    partial void DeleteUye(Uye instance);
    partial void InsertYayinEvi(YayinEvi instance);
    partial void UpdateYayinEvi(YayinEvi instance);
    partial void DeleteYayinEvi(YayinEvi instance);
    partial void InsertOduncKitap(OduncKitap instance);
    partial void UpdateOduncKitap(OduncKitap instance);
    partial void DeleteOduncKitap(OduncKitap instance);
    partial void InsertKitap(Kitap instance);
    partial void UpdateKitap(Kitap instance);
    partial void DeleteKitap(Kitap instance);
    #endregion
		
		public KutuphaneDataContext() : 
				base(global::KutuphaneApp.Properties.Settings.Default.KutuphaneDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Yazar> Yazars
		{
			get
			{
				return this.GetTable<Yazar>();
			}
		}
		
		public System.Data.Linq.Table<KitapTuru> KitapTurus
		{
			get
			{
				return this.GetTable<KitapTuru>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rols
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<Tip> Tips
		{
			get
			{
				return this.GetTable<Tip>();
			}
		}
		
		public System.Data.Linq.Table<Tur> Turs
		{
			get
			{
				return this.GetTable<Tur>();
			}
		}
		
		public System.Data.Linq.Table<Uye> Uyes
		{
			get
			{
				return this.GetTable<Uye>();
			}
		}
		
		public System.Data.Linq.Table<YayinEvi> YayinEvis
		{
			get
			{
				return this.GetTable<YayinEvi>();
			}
		}
		
		public System.Data.Linq.Table<OduncKitap> OduncKitaps
		{
			get
			{
				return this.GetTable<OduncKitap>();
			}
		}
		
		public System.Data.Linq.Table<Kitap> Kitaps
		{
			get
			{
				return this.GetTable<Kitap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yazar")]
	public partial class Yazar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private EntitySet<Kitap> _Kitaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public Yazar()
		{
			this._Kitaps = new EntitySet<Kitap>(new Action<Kitap>(this.attach_Kitaps), new Action<Kitap>(this.detach_Kitaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yazar_Kitap", Storage="_Kitaps", ThisKey="ID", OtherKey="YazarID")]
		public EntitySet<Kitap> Kitaps
		{
			get
			{
				return this._Kitaps;
			}
			set
			{
				this._Kitaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.Yazar = this;
		}
		
		private void detach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.Yazar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KitapTuru")]
	public partial class KitapTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _KitapID;
		
		private System.Guid _TurID;
		
		private EntityRef<Tur> _Tur;
		
		private EntityRef<Kitap> _Kitap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnKitapIDChanging(System.Guid value);
    partial void OnKitapIDChanged();
    partial void OnTurIDChanging(System.Guid value);
    partial void OnTurIDChanged();
    #endregion
		
		public KitapTuru()
		{
			this._Tur = default(EntityRef<Tur>);
			this._Kitap = default(EntityRef<Kitap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid KitapID
		{
			get
			{
				return this._KitapID;
			}
			set
			{
				if ((this._KitapID != value))
				{
					if (this._Kitap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKitapIDChanging(value);
					this.SendPropertyChanging();
					this._KitapID = value;
					this.SendPropertyChanged("KitapID");
					this.OnKitapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid TurID
		{
			get
			{
				return this._TurID;
			}
			set
			{
				if ((this._TurID != value))
				{
					if (this._Tur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTurIDChanging(value);
					this.SendPropertyChanging();
					this._TurID = value;
					this.SendPropertyChanged("TurID");
					this.OnTurIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tur_KitapTuru", Storage="_Tur", ThisKey="TurID", OtherKey="ID", IsForeignKey=true)]
		public Tur Tur
		{
			get
			{
				return this._Tur.Entity;
			}
			set
			{
				Tur previousValue = this._Tur.Entity;
				if (((previousValue != value) 
							|| (this._Tur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tur.Entity = null;
						previousValue.KitapTurus.Remove(this);
					}
					this._Tur.Entity = value;
					if ((value != null))
					{
						value.KitapTurus.Add(this);
						this._TurID = value.ID;
					}
					else
					{
						this._TurID = default(System.Guid);
					}
					this.SendPropertyChanged("Tur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kitap_KitapTuru", Storage="_Kitap", ThisKey="KitapID", OtherKey="ID", IsForeignKey=true)]
		public Kitap Kitap
		{
			get
			{
				return this._Kitap.Entity;
			}
			set
			{
				Kitap previousValue = this._Kitap.Entity;
				if (((previousValue != value) 
							|| (this._Kitap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kitap.Entity = null;
						previousValue.KitapTurus.Remove(this);
					}
					this._Kitap.Entity = value;
					if ((value != null))
					{
						value.KitapTurus.Add(this);
						this._KitapID = value.ID;
					}
					else
					{
						this._KitapID = default(System.Guid);
					}
					this.SendPropertyChanged("Kitap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private EntitySet<Uye> _Uyes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public Rol()
		{
			this._Uyes = new EntitySet<Uye>(new Action<Uye>(this.attach_Uyes), new Action<Uye>(this.detach_Uyes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Uye", Storage="_Uyes", ThisKey="ID", OtherKey="RolID")]
		public EntitySet<Uye> Uyes
		{
			get
			{
				return this._Uyes;
			}
			set
			{
				this._Uyes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uyes(Uye entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_Uyes(Uye entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tip")]
	public partial class Tip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private EntitySet<Kitap> _Kitaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public Tip()
		{
			this._Kitaps = new EntitySet<Kitap>(new Action<Kitap>(this.attach_Kitaps), new Action<Kitap>(this.detach_Kitaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tip_Kitap", Storage="_Kitaps", ThisKey="ID", OtherKey="TipID")]
		public EntitySet<Kitap> Kitaps
		{
			get
			{
				return this._Kitaps;
			}
			set
			{
				this._Kitaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.Tip = this;
		}
		
		private void detach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.Tip = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tur")]
	public partial class Tur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private EntitySet<KitapTuru> _KitapTurus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public Tur()
		{
			this._KitapTurus = new EntitySet<KitapTuru>(new Action<KitapTuru>(this.attach_KitapTurus), new Action<KitapTuru>(this.detach_KitapTurus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tur_KitapTuru", Storage="_KitapTurus", ThisKey="ID", OtherKey="TurID")]
		public EntitySet<KitapTuru> KitapTurus
		{
			get
			{
				return this._KitapTurus;
			}
			set
			{
				this._KitapTurus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KitapTurus(KitapTuru entity)
		{
			this.SendPropertyChanging();
			entity.Tur = this;
		}
		
		private void detach_KitapTurus(KitapTuru entity)
		{
			this.SendPropertyChanging();
			entity.Tur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uye")]
	public partial class Uye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Email;
		
		private string _AdSoyad;
		
		private int _DogumYili;
		
		private string _Sifre;
		
		private string _Telefon;
		
		private System.Nullable<System.Guid> _RolID;
		
		private EntitySet<OduncKitap> _OduncKitaps;
		
		private EntityRef<Rol> _Rol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnDogumYiliChanging(int value);
    partial void OnDogumYiliChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnRolIDChanging(System.Nullable<System.Guid> value);
    partial void OnRolIDChanged();
    #endregion
		
		public Uye()
		{
			this._OduncKitaps = new EntitySet<OduncKitap>(new Action<OduncKitap>(this.attach_OduncKitaps), new Action<OduncKitap>(this.detach_OduncKitaps));
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumYili", DbType="Int NOT NULL")]
		public int DogumYili
		{
			get
			{
				return this._DogumYili;
			}
			set
			{
				if ((this._DogumYili != value))
				{
					this.OnDogumYiliChanging(value);
					this.SendPropertyChanging();
					this._DogumYili = value;
					this.SendPropertyChanged("DogumYili");
					this.OnDogumYiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NChar(10)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> RolID
		{
			get
			{
				return this._RolID;
			}
			set
			{
				if ((this._RolID != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRolIDChanging(value);
					this.SendPropertyChanging();
					this._RolID = value;
					this.SendPropertyChanged("RolID");
					this.OnRolIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uye_OduncKitap", Storage="_OduncKitaps", ThisKey="ID", OtherKey="UyeID")]
		public EntitySet<OduncKitap> OduncKitaps
		{
			get
			{
				return this._OduncKitaps;
			}
			set
			{
				this._OduncKitaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Uye", Storage="_Rol", ThisKey="RolID", OtherKey="ID", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.Uyes.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.Uyes.Add(this);
						this._RolID = value.ID;
					}
					else
					{
						this._RolID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OduncKitaps(OduncKitap entity)
		{
			this.SendPropertyChanging();
			entity.Uye = this;
		}
		
		private void detach_OduncKitaps(OduncKitap entity)
		{
			this.SendPropertyChanging();
			entity.Uye = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YayinEvi")]
	public partial class YayinEvi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private EntitySet<Kitap> _Kitaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public YayinEvi()
		{
			this._Kitaps = new EntitySet<Kitap>(new Action<Kitap>(this.attach_Kitaps), new Action<Kitap>(this.detach_Kitaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YayinEvi_Kitap", Storage="_Kitaps", ThisKey="ID", OtherKey="YayinEviID")]
		public EntitySet<Kitap> Kitaps
		{
			get
			{
				return this._Kitaps;
			}
			set
			{
				this._Kitaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.YayinEvi = this;
		}
		
		private void detach_Kitaps(Kitap entity)
		{
			this.SendPropertyChanging();
			entity.YayinEvi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OduncKitap")]
	public partial class OduncKitap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _KitapID;
		
		private System.Guid _UyeID;
		
		private System.DateTime _BaslangicTarih;
		
		private System.DateTime _BitisTarih;
		
		private System.Nullable<bool> _GeriAlindiMi;
		
		private System.Nullable<System.DateTime> _GeriAlinmaTarihi;
		
		private EntityRef<Uye> _Uye;
		
		private EntityRef<Kitap> _Kitap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnKitapIDChanging(System.Guid value);
    partial void OnKitapIDChanged();
    partial void OnUyeIDChanging(System.Guid value);
    partial void OnUyeIDChanged();
    partial void OnBaslangicTarihChanging(System.DateTime value);
    partial void OnBaslangicTarihChanged();
    partial void OnBitisTarihChanging(System.DateTime value);
    partial void OnBitisTarihChanged();
    partial void OnGeriAlindiMiChanging(System.Nullable<bool> value);
    partial void OnGeriAlindiMiChanged();
    partial void OnGeriAlinmaTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnGeriAlinmaTarihiChanged();
    #endregion
		
		public OduncKitap()
		{
			this._Uye = default(EntityRef<Uye>);
			this._Kitap = default(EntityRef<Kitap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid KitapID
		{
			get
			{
				return this._KitapID;
			}
			set
			{
				if ((this._KitapID != value))
				{
					if (this._Kitap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKitapIDChanging(value);
					this.SendPropertyChanging();
					this._KitapID = value;
					this.SendPropertyChanged("KitapID");
					this.OnKitapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UyeID
		{
			get
			{
				return this._UyeID;
			}
			set
			{
				if ((this._UyeID != value))
				{
					if (this._Uye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUyeIDChanging(value);
					this.SendPropertyChanging();
					this._UyeID = value;
					this.SendPropertyChanged("UyeID");
					this.OnUyeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslangicTarih", DbType="Date NOT NULL")]
		public System.DateTime BaslangicTarih
		{
			get
			{
				return this._BaslangicTarih;
			}
			set
			{
				if ((this._BaslangicTarih != value))
				{
					this.OnBaslangicTarihChanging(value);
					this.SendPropertyChanging();
					this._BaslangicTarih = value;
					this.SendPropertyChanged("BaslangicTarih");
					this.OnBaslangicTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarih", DbType="Date NOT NULL")]
		public System.DateTime BitisTarih
		{
			get
			{
				return this._BitisTarih;
			}
			set
			{
				if ((this._BitisTarih != value))
				{
					this.OnBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._BitisTarih = value;
					this.SendPropertyChanged("BitisTarih");
					this.OnBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeriAlindiMi", DbType="Bit")]
		public System.Nullable<bool> GeriAlindiMi
		{
			get
			{
				return this._GeriAlindiMi;
			}
			set
			{
				if ((this._GeriAlindiMi != value))
				{
					this.OnGeriAlindiMiChanging(value);
					this.SendPropertyChanging();
					this._GeriAlindiMi = value;
					this.SendPropertyChanged("GeriAlindiMi");
					this.OnGeriAlindiMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeriAlinmaTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> GeriAlinmaTarihi
		{
			get
			{
				return this._GeriAlinmaTarihi;
			}
			set
			{
				if ((this._GeriAlinmaTarihi != value))
				{
					this.OnGeriAlinmaTarihiChanging(value);
					this.SendPropertyChanging();
					this._GeriAlinmaTarihi = value;
					this.SendPropertyChanged("GeriAlinmaTarihi");
					this.OnGeriAlinmaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uye_OduncKitap", Storage="_Uye", ThisKey="UyeID", OtherKey="ID", IsForeignKey=true)]
		public Uye Uye
		{
			get
			{
				return this._Uye.Entity;
			}
			set
			{
				Uye previousValue = this._Uye.Entity;
				if (((previousValue != value) 
							|| (this._Uye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uye.Entity = null;
						previousValue.OduncKitaps.Remove(this);
					}
					this._Uye.Entity = value;
					if ((value != null))
					{
						value.OduncKitaps.Add(this);
						this._UyeID = value.ID;
					}
					else
					{
						this._UyeID = default(System.Guid);
					}
					this.SendPropertyChanged("Uye");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kitap_OduncKitap", Storage="_Kitap", ThisKey="KitapID", OtherKey="ID", IsForeignKey=true)]
		public Kitap Kitap
		{
			get
			{
				return this._Kitap.Entity;
			}
			set
			{
				Kitap previousValue = this._Kitap.Entity;
				if (((previousValue != value) 
							|| (this._Kitap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kitap.Entity = null;
						previousValue.OduncKitaps.Remove(this);
					}
					this._Kitap.Entity = value;
					if ((value != null))
					{
						value.OduncKitaps.Add(this);
						this._KitapID = value.ID;
					}
					else
					{
						this._KitapID = default(System.Guid);
					}
					this.SendPropertyChanged("Kitap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kitap")]
	public partial class Kitap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Adi;
		
		private int _SayfaSayisi;
		
		private System.Guid _YazarID;
		
		private string _Dili;
		
		private System.Nullable<System.Guid> _YayinEviID;
		
		private System.Guid _TipID;
		
		private string _ISBN;
		
		private System.DateTime _AlimTarihi;
		
		private System.DateTime _BasimTarihi;
		
		private decimal _Fiyati;
		
		private string _ResimURL;
		
		private System.Nullable<bool> _Aktif;
		
		private System.Nullable<int> _OkunmaSayisi;
		
		private EntitySet<KitapTuru> _KitapTurus;
		
		private EntitySet<OduncKitap> _OduncKitaps;
		
		private EntityRef<Tip> _Tip;
		
		private EntityRef<YayinEvi> _YayinEvi;
		
		private EntityRef<Yazar> _Yazar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSayfaSayisiChanging(int value);
    partial void OnSayfaSayisiChanged();
    partial void OnYazarIDChanging(System.Guid value);
    partial void OnYazarIDChanged();
    partial void OnDiliChanging(string value);
    partial void OnDiliChanged();
    partial void OnYayinEviIDChanging(System.Nullable<System.Guid> value);
    partial void OnYayinEviIDChanged();
    partial void OnTipIDChanging(System.Guid value);
    partial void OnTipIDChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnAlimTarihiChanging(System.DateTime value);
    partial void OnAlimTarihiChanged();
    partial void OnBasimTarihiChanging(System.DateTime value);
    partial void OnBasimTarihiChanged();
    partial void OnFiyatiChanging(decimal value);
    partial void OnFiyatiChanged();
    partial void OnResimURLChanging(string value);
    partial void OnResimURLChanged();
    partial void OnAktifChanging(System.Nullable<bool> value);
    partial void OnAktifChanged();
    partial void OnOkunmaSayisiChanging(System.Nullable<int> value);
    partial void OnOkunmaSayisiChanged();
    #endregion
		
		public Kitap()
		{
			this._KitapTurus = new EntitySet<KitapTuru>(new Action<KitapTuru>(this.attach_KitapTurus), new Action<KitapTuru>(this.detach_KitapTurus));
			this._OduncKitaps = new EntitySet<OduncKitap>(new Action<OduncKitap>(this.attach_OduncKitaps), new Action<OduncKitap>(this.detach_OduncKitaps));
			this._Tip = default(EntityRef<Tip>);
			this._YayinEvi = default(EntityRef<YayinEvi>);
			this._Yazar = default(EntityRef<Yazar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SayfaSayisi", DbType="Int NOT NULL")]
		public int SayfaSayisi
		{
			get
			{
				return this._SayfaSayisi;
			}
			set
			{
				if ((this._SayfaSayisi != value))
				{
					this.OnSayfaSayisiChanging(value);
					this.SendPropertyChanging();
					this._SayfaSayisi = value;
					this.SendPropertyChanged("SayfaSayisi");
					this.OnSayfaSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YazarID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid YazarID
		{
			get
			{
				return this._YazarID;
			}
			set
			{
				if ((this._YazarID != value))
				{
					if (this._Yazar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYazarIDChanging(value);
					this.SendPropertyChanging();
					this._YazarID = value;
					this.SendPropertyChanged("YazarID");
					this.OnYazarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dili", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Dili
		{
			get
			{
				return this._Dili;
			}
			set
			{
				if ((this._Dili != value))
				{
					this.OnDiliChanging(value);
					this.SendPropertyChanging();
					this._Dili = value;
					this.SendPropertyChanged("Dili");
					this.OnDiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YayinEviID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> YayinEviID
		{
			get
			{
				return this._YayinEviID;
			}
			set
			{
				if ((this._YayinEviID != value))
				{
					if (this._YayinEvi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYayinEviIDChanging(value);
					this.SendPropertyChanging();
					this._YayinEviID = value;
					this.SendPropertyChanged("YayinEviID");
					this.OnYayinEviIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid TipID
		{
			get
			{
				return this._TipID;
			}
			set
			{
				if ((this._TipID != value))
				{
					if (this._Tip.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipIDChanging(value);
					this.SendPropertyChanging();
					this._TipID = value;
					this.SendPropertyChanged("TipID");
					this.OnTipIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(50)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlimTarihi", DbType="Date NOT NULL")]
		public System.DateTime AlimTarihi
		{
			get
			{
				return this._AlimTarihi;
			}
			set
			{
				if ((this._AlimTarihi != value))
				{
					this.OnAlimTarihiChanging(value);
					this.SendPropertyChanging();
					this._AlimTarihi = value;
					this.SendPropertyChanged("AlimTarihi");
					this.OnAlimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasimTarihi", DbType="Date NOT NULL")]
		public System.DateTime BasimTarihi
		{
			get
			{
				return this._BasimTarihi;
			}
			set
			{
				if ((this._BasimTarihi != value))
				{
					this.OnBasimTarihiChanging(value);
					this.SendPropertyChanging();
					this._BasimTarihi = value;
					this.SendPropertyChanged("BasimTarihi");
					this.OnBasimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyati", DbType="Money NOT NULL")]
		public decimal Fiyati
		{
			get
			{
				return this._Fiyati;
			}
			set
			{
				if ((this._Fiyati != value))
				{
					this.OnFiyatiChanging(value);
					this.SendPropertyChanging();
					this._Fiyati = value;
					this.SendPropertyChanged("Fiyati");
					this.OnFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResimURL", DbType="NVarChar(50)")]
		public string ResimURL
		{
			get
			{
				return this._ResimURL;
			}
			set
			{
				if ((this._ResimURL != value))
				{
					this.OnResimURLChanging(value);
					this.SendPropertyChanging();
					this._ResimURL = value;
					this.SendPropertyChanged("ResimURL");
					this.OnResimURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktif", DbType="Bit")]
		public System.Nullable<bool> Aktif
		{
			get
			{
				return this._Aktif;
			}
			set
			{
				if ((this._Aktif != value))
				{
					this.OnAktifChanging(value);
					this.SendPropertyChanging();
					this._Aktif = value;
					this.SendPropertyChanged("Aktif");
					this.OnAktifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkunmaSayisi", DbType="Int")]
		public System.Nullable<int> OkunmaSayisi
		{
			get
			{
				return this._OkunmaSayisi;
			}
			set
			{
				if ((this._OkunmaSayisi != value))
				{
					this.OnOkunmaSayisiChanging(value);
					this.SendPropertyChanging();
					this._OkunmaSayisi = value;
					this.SendPropertyChanged("OkunmaSayisi");
					this.OnOkunmaSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kitap_KitapTuru", Storage="_KitapTurus", ThisKey="ID", OtherKey="KitapID")]
		public EntitySet<KitapTuru> KitapTurus
		{
			get
			{
				return this._KitapTurus;
			}
			set
			{
				this._KitapTurus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kitap_OduncKitap", Storage="_OduncKitaps", ThisKey="ID", OtherKey="KitapID")]
		public EntitySet<OduncKitap> OduncKitaps
		{
			get
			{
				return this._OduncKitaps;
			}
			set
			{
				this._OduncKitaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tip_Kitap", Storage="_Tip", ThisKey="TipID", OtherKey="ID", IsForeignKey=true)]
		public Tip Tip
		{
			get
			{
				return this._Tip.Entity;
			}
			set
			{
				Tip previousValue = this._Tip.Entity;
				if (((previousValue != value) 
							|| (this._Tip.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tip.Entity = null;
						previousValue.Kitaps.Remove(this);
					}
					this._Tip.Entity = value;
					if ((value != null))
					{
						value.Kitaps.Add(this);
						this._TipID = value.ID;
					}
					else
					{
						this._TipID = default(System.Guid);
					}
					this.SendPropertyChanged("Tip");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YayinEvi_Kitap", Storage="_YayinEvi", ThisKey="YayinEviID", OtherKey="ID", IsForeignKey=true)]
		public YayinEvi YayinEvi
		{
			get
			{
				return this._YayinEvi.Entity;
			}
			set
			{
				YayinEvi previousValue = this._YayinEvi.Entity;
				if (((previousValue != value) 
							|| (this._YayinEvi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._YayinEvi.Entity = null;
						previousValue.Kitaps.Remove(this);
					}
					this._YayinEvi.Entity = value;
					if ((value != null))
					{
						value.Kitaps.Add(this);
						this._YayinEviID = value.ID;
					}
					else
					{
						this._YayinEviID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("YayinEvi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yazar_Kitap", Storage="_Yazar", ThisKey="YazarID", OtherKey="ID", IsForeignKey=true)]
		public Yazar Yazar
		{
			get
			{
				return this._Yazar.Entity;
			}
			set
			{
				Yazar previousValue = this._Yazar.Entity;
				if (((previousValue != value) 
							|| (this._Yazar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Yazar.Entity = null;
						previousValue.Kitaps.Remove(this);
					}
					this._Yazar.Entity = value;
					if ((value != null))
					{
						value.Kitaps.Add(this);
						this._YazarID = value.ID;
					}
					else
					{
						this._YazarID = default(System.Guid);
					}
					this.SendPropertyChanged("Yazar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KitapTurus(KitapTuru entity)
		{
			this.SendPropertyChanging();
			entity.Kitap = this;
		}
		
		private void detach_KitapTurus(KitapTuru entity)
		{
			this.SendPropertyChanging();
			entity.Kitap = null;
		}
		
		private void attach_OduncKitaps(OduncKitap entity)
		{
			this.SendPropertyChanging();
			entity.Kitap = this;
		}
		
		private void detach_OduncKitaps(OduncKitap entity)
		{
			this.SendPropertyChanging();
			entity.Kitap = null;
		}
	}
}
#pragma warning restore 1591
